### PR TITLE
Add a name parametter

### PR DESCRIPTION
**Pull request by CapMousse**
Add a name parametter to change the zest object name

### CODE REVIEW

**Comment by pyrsmk** [comment]
Hi,

I wondered, why do you need this?

**Comment by CapMousse** [comment]
Beause if an other module is named "zest" in my project, i will have a
comflict.

With this parameter, we can easily change the name wihout change the core
code
Le 9 nov. 2011 13:12, "Aurlien Delogu" <
reply@reply.github.com>
a crit :

**Comment by pyrsmk** [comment]
Shouldn't it be better to change your library scope? Or rather use the [Modules spec](http://wiki.commonjs.org/wiki/Modules/1.1) used in many projects (ender, and nodejs?). As zest is integrated to ender, I think it's better to improve it on this point.

We should never change library name/scope into the script itself... It seems to be pretty bad practice :s

**Comment by chjj** [comment]
How about a compromise? I can add a .noConflict function instead.

**Comment by CapMousse** [comment]
chjj, yeah it will be very usefull =)

**Comment by pyrsmk** [comment]
(maybe it'll better to speak english, for those who read us :p)

I understand well your point of view but it's not really efficient to go into the library to change the placeholder :s I agree with @chjj's noConflict idea.

**Comment by chjj** [comment]
Okay, implemented: 659b1e243fb62bf21d562efc7a79cc9a25166172

I also refactored zest a bit, hopefully with some performance improvements. Caching is now enabled by default.

**Pull request closed without merging**
